### ISSUE TITLE
Authenticated Information Disclosure Vulnerability

### ISSUE THREAD

**Issue by PluginVulnerabilities** [KingYes/wordpress-aryo-activity-log#89]
The AJAX accessible function ajax_aal_get_properties(), in the file /classes/class-aal-settings.php, is accessible to any logged in user despite it looking like it is only intended to be accessed by Administrator level users. Through that certain non-public information on the users of the website can be disclosed.

**Comment by maor** [comment]
Since the capability for viewing AAL pages can be selectively assigned to specific roles, this isn't really a security issue. However it's probably a best practice to add the capability check anyway.

Thanks for bringing this into our attention, @PluginVulnerabilities!

@KingYes what are your thoughts on this?

**Comment by PluginVulnerabilities** [comment]
The function is accessible without the user's role being assigned to view AAL pages, as it is accessible to any logged in user, so it is a security issue.
